# Generated by Django 5.1.6 on 2025-02-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlSensei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(db_column='User_ID', primary_key=True, serialize=False)),
                ('password', models.TextField(db_column='Password')),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('full_name', models.CharField(db_column='Full_Name', max_length=255)),
                ('registration_date', models.DateTimeField(blank=True, db_column='Registration_Date', null=True)),
                ('last_login_date', models.DateTimeField(blank=True, db_column='Last_Login_Date', null=True)),
                ('status', models.CharField(db_column='Status', max_length=50)),
                ('role', models.CharField(db_column='Role', max_length=50)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
    ]
