# Generated by Django 5.1.6 on 2025-02-21 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlSensei', '0002_users_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(db_column='Email', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='users',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Registration_Date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(db_column='Role', default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(db_column='Status', default='active', max_length=50),
        ),
    ]
